### ISSUE TITLE
SyntaxError in the given example

### ISSUE THREAD

**Issue by evprkr** [vierofernando/python-weather#1]
Using the example found in the README.md and on the PyPi page, I'm getting the error:

```
SyntaxError: 'await' outside function
```

**Comment by vierofernando** [comment]
You can fix this by running it in an async function.
e.g: 
```py
from asyncio import get_event_loop
async def main():
    # paste example here

get_event_loop().run_until_complete(main())
```

**Comment by evprkr** [comment]
> You can fix this by running it in an async function.
> e.g:
> 
> ```python
> from asyncio import get_event_loop
> async def main():
>     # paste example here
> 
> get_event_loop().run_until_complete(main())
> ```

Excellent! Thank you. Not super familiar with async yet. Is there a way to run this without async if one should want to?
