### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by oscie57** [vierofernando/python-weather#10]
Is someone able to make a file that makes use of everything this can do? There's certain things I want to do with it but I wouldn't really know how (and I'm sorta new to Python, so it'd be hard to try and figure what it can do out myself)

**Comment by vierofernando** [comment]
so far, the only thing it can do is requesting to the msn weather API! so pretty much everything in the readme is what it only can do :)

**Comment by Oscie57** [comment]
Ah, thanks!
