### ISSUE TITLE
Typo making 'current' object unusable

### ISSUE THREAD

**Issue by CiaronHowell** [vierofernando/python-weather#11]
Hi, stumbled upon your python module today and wanted to use it. Whilst testing it out, I found that the 'current' object of the weather class cannot be used due to a small typo of current in the if statement located in 'response.py' line 160 `return CurrentForecast(current) if currrent else None`.

Thought I'd be better creating an issue rather than forking and creating a pull request for such a small thing.

Great work on the module, still going to use it!

**Comment by vierofernando** [comment]
thanks for the bug report! this issue will be fixed soon in a future update.

**Comment by vierofernando** [comment]
ok this issue is fixed in version 0.3.5. please update your version! :)
