### ISSUE TITLE
Setting the format has no effect

### ISSUE THREAD

**Issue by ZechCodes** [vierofernando/python-weather#14]
Setting the temperature format to imperial has no effect, temperatures are still returned in metric.

The issue is that the `session` arg is being passed from `python_weather.client.Client.__init__` as the first arg to `python_weather.rest.HTTPClient`. The `HTTPClient` expects the session to be the last arg.

https://github.com/vierofernando/python-weather/blob/e7908a2e47def82bfbb092ac73e159e43d99fb01/python_weather/rest.py#L12

https://github.com/vierofernando/python-weather/blob/e7908a2e47def82bfbb092ac73e159e43d99fb01/python_weather/client.py#L13

**Comment by vierofernando** [comment]
thanks for the bug report! will fix this in a future update really soon.

**Comment by vierofernando** [comment]
fixed on version [0.3.6](https://pypi.org/project/python-weather/0.3.6/), please let me know if other bug occurs, thanks!
