### ISSUE TITLE
weather results not updating

### ISSUE THREAD

**Issue by daniellukeahead** [vierofernando/python-weather#17]
running the example.py at 2pm on Nov,13 2021 in Canada , getting the results that seems not updated: 

26
2021-11-09 00:00:00 Clear 36
2021-11-10 00:00:00 Cloudy 33
2021-11-11 00:00:00 Cloudy 31
2021-11-12 00:00:00 Mostly Cloudy 43
2021-11-13 00:00:00 Sunny 38

Used to work well, what could be wrong?

**Comment by caseybecking** [comment]
Same, not seeing any new data.

**Comment by daniellukeahead** [comment]
It was functional again since yesterday.  Nothing touched. No idea what happened. But all good now.
