### ISSUE TITLE
DeprecationWarning: There is no current event loop

### ISSUE THREAD

**Issue by ctricot** [vierofernando/python-weather#19]
With Python 3.10 replace 
`loop = asyncio.get_event_loop()`

By
` loop = asyncio.new_event_loop()`

**Comment by vierofernando** [comment]
got it, thanks

**Comment by vierofernando** [comment]
landed in this [commit](https://github.com/vierofernando/python-weather/commit/5aed91f7b46cca54b6a8b761028aa31b2389dbbe).
