### ISSUE TITLE
Example Script ignores format and find

### ISSUE THREAD

**Issue by Traace** [vierofernando/python-weather#7]
Plattfrom: Windows
Python Version: 3.9.5
Using your example code.

Issue: 
1. Script always defaults to IMPERIAL, even if METRIC is set.
2. Script always defaults to location "Washington, DC", even if something else is set.

What I expect:
Example should make use of format=python_weather.METRIC if set
Weather should be fetched for the specific location with client.find

I downloaded python-weather via pip. Maybe its a old version?

**Comment by vierofernando** [comment]
thanks for the bug report, will look into it! :)

**Comment by vierofernando** [comment]
ok, this issue has been fixed in version 0.3.1. try updating your package to at least version 0.3.1, hope it helps! :)

https://pypi.org/project/python-weather/0.3.1/
