### ISSUE TITLE
The use of the package is not clear

### ISSUE THREAD

**Issue by tomimartin01** [vierofernando/python-weather#8]
Hi!

This package solves a real issue for me but I don't know how to use it, there's few information about it, the example runs ok. I'd like to change the metrics to Celsius and there's no information on how to do it and  if  it's possible to get the forecast of other cities or it works only for Washington?

Thanks

**Comment by vierofernando** [comment]
hi!

firstly, it supports two measuring units, metric and imperial, and secondly, it works for other cities and locations too (if you haven't knew about #7 please update to the latest version)

```py
import python_weather

# to use imperial units (fahrenheit, mph, etc.)
client = python_weather.Client(format=python_weather.IMPERIAL)

# to use metric units (celcius, kph, etc.)
client = python_weather.Client(format=python_weather.METRIC)
```

you can request to other cities too, the API supports a wide variety of locations. e.g:
```py
# wrap this snippet in an async function
response = await client.find('Berlin')
print(response)
```

hope that helps!

**Comment by tomimartin01** [comment]
Thanks !! that helps a lot. I'd like to know if there's a list of the available cities . I'm in South America (Argentina) and I'd like the forecast for at least Buenos Aires.

Thanks for your quick response.

**Comment by vierofernando** [comment]
no problem, have a nice day! :)
