### ISSUE TITLE
Incorrect minimum Python version is specified

### ISSUE THREAD

**Issue by MarkKoz** [vierofernando/python-weather#9]
The `:=` operator, which is available only in Python 3.8 and higher, is used here https://github.com/vierofernando/python-weather/blob/main/python_weather/rest.py#L25

However, the package defined the minimum Python version as 3.7 here https://github.com/vierofernando/python-weather/blob/main/setup.py#L34

Users on 3.7 will experience a `SyntaxError`. Either specify the minimum Python version as 3.8, or avoid using the `:=` operator to maintain 3.7 compatibility.

**Comment by vierofernando** [comment]
thanks for the issue! will make a support for python 3.7 soon.

**Comment by vierofernando** [comment]
ok, this issue is resolved in version 0.3.4.
